name: svetly
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#011d18'
    - '#c3b8a3'
    - '#496f57'
    - '#05412a'
  brandStrength: 1
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 1
purpose: []
