name: "Svetly's Grid Site"
favicon: null
layout_spectrum: 0.10088
typography_spectrum: 0.4693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-63442818-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d626d'
    - '#26343b'
    - '#778e9b'
    - '#abb9c2'
    - '#dbe2e6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
