analytics: {}
color:
  brandColors:
    - '#fbfbfb'
    - '#011d18'
    - '#c3b8a3'
    - '#496f57'
    - '#05412a'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0.5
  saturation: 0.519736
cta: {}
layout_spectrum: 0.38095
name: svetly
opengraph: {}
purpose: []
typography_spectrum: 0.32813
