name: svetly
favicon: null
layout_spectrum: 0.42501
typography_spectrum: 0.32813
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#011d18'
    - '#c3b8a3'
    - '#496f57'
    - '#05412a'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 1
purpose: []
