name: "Svetly's Grid Site"
favicon: null
layout_spectrum: 0.41667
typography_spectrum: 0.4693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-63442818-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfd4e3'
    - '#3e3a30'
    - '#737173'
    - '#050000'
    - '#8c091a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
